### ISSUE TITLE
Unable to claim prize

### ISSUE THREAD

**Issue by Farsinuce** [AddstarMC/BungeeUnscramble#1]
Dear Schmoller / Addstar,

Inspired by your BungeeUnscramble project I am trying to install it on my own servers.
However, what ever I try, I am unable to claim a prize after winning a game.

This is my auto.yml (don't mind the low timing values):
http://pastebin.com/Qd1w73DB
I also tried using numbers for data values instead.

Here's a screenshot _after_ I have won and typed **/us claim** (nothing happens except unclaimed.yml being emptied).
![bungeeunscramble](https://cloud.githubusercontent.com/assets/5788348/6012509/3a58e64c-ab49-11e4-83cc-24e0ea77b357.jpg)
Sadly, there are no console errors.

It would be kind of you, if you could point me in the right direction.
Thank you for sharing this project.

Regards,
Sinuce // Asger, Denmark

UPDATE:
Oh, and here is my config.yml if it can be of any help:
http://pastebin.com/HWzKedSe

**Comment by Schmoller** [comment]
Hi there, we designed this bungee plugin to use CommandHelper on the bukkit/spigot servers. Inside the jar is 'unscramble.ms' which is a CommandHelper script which handles claiming. It only needs to be placed on servers players are allowed to claim on.

**Comment by Farsinuce** [comment]
Hello Schmoller ^^
Looking at your repository I can assume that you are a busy person - so thank you for your time and for the swift reply.

I tried installing [CommandHelper Build #2827](http://builds.enginehub.org/job/commandhelper/last-successful?branch=master) on two Spigot servers players are allowed to claim on. Alas the issue persists. Do I need to add some script to CommandHelper? Or am I missing something as basic as placing the BungeeUnscramble .jar into the Spigot server folders as well? ._.

At some point I am also looking to recompile BungeeUnscramble so that I can edit the messages, translating them into Danish. Does your project have any depencensies that I need to know of other than Yamler (build #59 I assume) and CommandHelper?

**Comment by Schmoller** [comment]
I don't know if you did or not as you didn't mention it, but place the 'unscramble.ms' file in the CommandHelper/LocalPackages folder on each spigot server. Once there, it should run just fine (after reloading of course :) ).

As for recompiling it, just use maven. It will handle getting all the dependencies for you.

**Comment by Farsinuce** [comment]
Ohhh, I get it now!
I misunderstood you at first.
It's working flawlessly now.

Thank you for helping me out.
I'm not sure how to return the favour.
Let me know if you need feedback on BungeeUnscramble or the sorts :)
